### ISSUE TITLE
Don't convert ZKCert to JSON before encryption

### ISSUE THREAD

**Issue by HarmlessEvil** [Galactica-corp/galactica-monorepo#28]
https://github.com/Galactica-corp/galactica-monorepo/blob/bd4e35e1dcafda2c5673687d6d185090fd3321c0/packages/zk-certificates/lib/zkCertificate.ts#L145-L150

According to `encryptSafely` implementation, it already converts the data into JSON: https://github.com/MetaMask/eth-sig-util/blob/10206bf2f16f0b47b1f2da9a9cfbb39c6a7a7800/src/encryption.ts#L129-L141

If we encode it again, we'll be encrypting something like this: `{\"holderCommitment\":\"12345\"}` instead of `{"holderCommitment":"12345"}` (note that escape sequences will be present in the message to be encrypted), which will bloat the message size. According to the library, it's strongly advised not to encrypt large messages ([original](https://nacl.cr.yp.to/valid.html), [GoLang implementation](https://pkg.go.dev/golang.org/x/crypto@v0.15.0/nacl/box#pkg-overview)).

But if this is a requirement from snap to encrypt the JSON string instead of your data, then I'm incorrect. I can't check it, so if anyone can explain how to do it, I would appreciate it.

**Comment by zwilling** [comment]
Thanks for opening the issue. I'll change it.

**Comment by zwilling** [comment]
Solved in https://github.com/Galactica-corp/galactica-monorepo/commit/3eef3a1e4f2126ce59cd5d675fd1861cc67e4ad3
