### ISSUE TITLE
Inconsistent transaction parameter encoding

### ISSUE THREAD

**Issue by HarmlessEvil** [Galactica-corp/galactica-monorepo#29]
https://github.com/Galactica-corp/galactica-monorepo/blob/fb3dd6cda960d22eb858f327c14a552acddbcdce/packages/zk-certificates/tasks/revokeZKKYC.ts#L82-L86

As you can see in this snippet, `leafHash` is encoded `fromDecToHex`, whereas each hash in Merkle proof is encoded `fromHexToBytes32(fromDecToHex)`. Also in `createZKKYC` both of the parameters encoded `fromHexToBytes32(fromDecToHex)`.

I can't check it either, but it really looks wrong to me.

**Comment by zwilling** [comment]
Yep, you are right, it should also be in Bytes32.
